# Generated by Django 2.0.1 on 2018-03-05 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='birthdate',
            field=models.DateField(null=True),
        ),
    ]
